server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  output:
    ansi:
      enabled: always
  datasource:
    username: ${USER_DB}
    password: ${PASS_DB}
    url: jdbc:mysql://localhost:3306/d3_medialuna?useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect